const $ = id => document.getElementById(id), value = id => $(id).value.trim(); let generated = '';
        const servers = { pr3s1: { public: '143.110.244.41', vpn: '192.168.112.1' }, pr3s2: { public: '64.227.158.172', vpn: '192.168.113.1' }, pr3s3: { public: '139.59.168.36', vpn: '192.168.116.1' } };
        function toggle() { let vpn = value('wanReach') === 'private', selected = value('publicServer'), server = servers[selected]; $('staticFields').classList.toggle('hidden', value('wanMode') !== 'static'); $('pppoeWanFields').classList.toggle('hidden', value('wanMode') !== 'pppoe'); $('vpnFields').classList.toggle('hidden', !vpn); $('radiusIp').readOnly = !!server; $('vpnEndpoint').readOnly = !!server; if (server) { $('radiusIp').value = vpn ? server.vpn : server.public; $('vpnEndpoint').value = server.public } else if (selected !== 'custom') { $('radiusIp').value = ''; $('vpnEndpoint').value = '' } $('radiusIp').placeholder = selected === 'custom' ? 'Enter RADIUS IP' : 'Select a server'; $('vpnEndpoint').placeholder = selected === 'custom' ? 'Enter L2TP server IP' : 'Select a server'; $('bridgeFields').classList.toggle('hidden', value('lanMode') !== 'bridge'); $('vlanFields').classList.toggle('hidden', value('lanMode') !== 'vlan'); $('ipsecField').classList.toggle('hidden', value('vpnIpsec') !== 'yes'); }
        ['wanMode', 'wanReach', 'lanMode', 'vpnIpsec'].forEach(id => $(id).addEventListener('change', toggle)); $('publicServer').addEventListener('change', () => { $('radiusIp').value = ''; $('vpnEndpoint').value = ''; toggle() }); toggle();
        function toggleHotspot() { $('hotspotFields').classList.toggle('hidden', !$('enableHotspot').checked); hotspotPreview() }
        $('enableHotspot').addEventListener('change', toggleHotspot); $('hotspotSubnet').addEventListener('input', hotspotPreview); toggleHotspot();
        function fail(s) { throw Error(s) }
        function ip(s) { let p = s.split('.'); if (p.length !== 4 || p.some(x => !/^(0|[1-9]\d{0,2})$/.test(x) || +x > 255)) fail('Invalid IPv4 address: ' + s); return p.reduce((n, x) => (n * 256 + Number(x)) >>> 0, 0) }
        function fmt(n) { return [24, 16, 8, 0].map(b => (n >>> b) & 255).join('.') }
        function cidr(s) { let m = /^([^/]+)\/(\d{1,2})$/.exec(s); if (!m) fail('Use IP/CIDR format: ' + s); let bits = +m[2]; if (bits < 16 || bits > 30) fail('Customer pools need a prefix from /16 to /30.'); let addr = ip(m[1]), size = 2 ** (32 - bits), net = Math.floor(addr / size) * size; return { addr, net, size, bits, last: net + size - 1 } }
        function privateRange(n, size) { let end = n + size - 1; return (n >= ip('10.0.0.0') && end <= ip('10.255.255.255')) || (n >= ip('172.16.0.0') && end <= ip('172.31.255.255')) || (n >= ip('192.168.0.0') && end <= ip('192.168.255.255')) }
        function calcPools(subnet) { let a = cidr(subnet); if (!privateRange(a.net, a.size)) fail('Active subnet must be private'); let start = a.net + 2; if (start >= a.last) fail('Subnet too small for a pool starting at network + 2'); a.addr = a.net + 1; let anchor = ip('1.1.1.0'), net = Math.floor(anchor / a.size) * a.size, e = { net, size: a.size, bits: a.bits, last: net + a.size - 1 }; if (overlap(a, e)) fail('Active subnet overlaps the fixed expired range'); let expStart = e.net + 2, expEnd = e.last - 1; return { a, e, start, expStart, expEnd } }
        function pools() { return calcPools(value('lanAddress')) }
        function rows(id, min, max) { return value(id).split(/\r?\n/).map(s => s.trim()).filter(Boolean).map((line, i) => { let parts = line.split(',').map(s => s.trim()); if (parts.length < min || parts.length > max || parts.slice(0, min).some(s => !s)) fail(id + ' line ' + (i + 1) + ': expected ' + min + (max !== min ? '–' + max : '') + ' comma-separated fields'); return parts }) }
        function overlap(x, y) { return x.net < y.net + y.size && y.net < x.net + x.size }
        function calcHotspotSubnet(subnet) { let a = cidr(subnet), start = a.net + 2, end = a.last - 1; if (start > end) fail('Hotspot subnet must have at least one usable DHCP address after the gateway.'); a.addr = a.net + 1; return { a, start, end } }
        function hotspotPreview() { if (!$('enableHotspot').checked) { $('hotspotPreview').textContent = ''; return } try { let { a, start, end } = calcHotspotSubnet(value('hotspotSubnet')); $('hotspotPreview').textContent = 'Gateway: ' + fmt(a.addr) + ' | DHCP pool: ' + fmt(start) + '–' + fmt(end) } catch (err) { $('hotspotPreview').textContent = err.message } }
        function preview() { try { let { a, e, start, expStart, expEnd } = pools(); $('poolPreview').textContent = 'PPPoE local: ' + fmt(a.addr) + ' | Active: ' + fmt(a.net) + '/' + a.bits + ' → ' + fmt(start) + '–' + fmt(a.last - 1) + ' | Expired: ' + fmt(e.net) + '/' + e.bits + ' → ' + fmt(expStart) + '–' + fmt(expEnd) } catch (err) { $('poolPreview').textContent = err.message } }
        $('lanAddress').addEventListener('input', preview); preview();
        function ident(s, name) { if (!/^[A-Za-z0-9_.-]{1,48}$/.test(s)) fail(name + ' must contain only letters, digits, _, . or -'); return s }
        function literal(s, name) { if (!s || /[\r\n"\\]/.test(s)) fail(name + ' is required and cannot include a quote, backslash or newline'); return '"' + s + '"' }
        function host(s, name) { if (!s || !/^[-a-zA-Z0-9.]+$/.test(s)) fail('Invalid ' + name); return s }
        function generate() {
            let lines = ['# RouterOS 7 - review names, addressing, RADIUS route and firewall ordering before import', '# Use Safe Mode for remote changes. Export and back up the router first.'];
            let wi = ident(value('wanInterface'), 'WAN interface'), physicalWan = wi, li = ident(value('lanInterface'), 'Customer interface'); if (wi === li) fail('WAN and customer interfaces must differ');
            let { a, e, start, expStart, expEnd } = pools(); let selected = value('publicServer'); if (!selected) fail('Select PR3S1, PR3S2, PR3S3, or Custom'); let radius = fmt(ip(value('radiusIp'))), secret = literal(value('radiusSecret'), 'RADIUS secret'), service = literal(value('service'), 'Service name'); let mode = value('lanMode'), customer = li;
            let wanOut = wi, wanClientName = value('wanMode') === 'pppoe' ? ident(value('wanPppoeName'), 'PPPoE WAN name') : '', wanVlan = value('wanVlanId') ? ident(value('wanVlanName'), 'WAN VLAN name') : ''; if (wanClientName && (wanClientName === wi || wanClientName === li || wanClientName === wanVlan)) fail('PPPoE WAN name conflicts with another interface'); if (wanVlan) { let vid = Number(value('wanVlanId')); if (!Number.isInteger(vid) || vid < 1 || vid > 4094) fail('WAN VLAN ID must be 1–4094'); if (wanVlan === wi || wanVlan === li) fail('WAN VLAN name conflicts with another interface') }
            if (mode === 'bridge') { customer = ident(value('bridgeName'), 'Bridge name'); let extra = value('bridgeExtra') ? value('bridgeExtra').split(',').map(s => ident(s.trim(), 'Bridge port')) : [], ports = [li, ...extra]; if (new Set(ports).size !== ports.length) fail('Bridge ports must be unique'); if (ports.includes(wi) || ports.includes(wanVlan) || ports.includes(wanClientName)) fail('WAN interface cannot be a customer bridge port'); if (customer === wi || ports.includes(customer) || customer === wanClientName || customer === wanVlan) fail('Bridge name conflicts with another interface'); lines.push('/interface bridge', 'add name=' + customer, '/interface bridge port', ...ports.map(port => 'add bridge=' + customer + ' interface=' + port)) }
            if (mode === 'vlan') { customer = ident(value('vlanName'), 'VLAN name'); let id = +value('vlanId'); if (!Number.isInteger(id) || id < 1 || id > 4094) fail('VLAN ID must be 1–4094'); if (customer === li || customer === wi || customer === wanClientName || customer === wanVlan) fail('VLAN name conflicts with another interface'); lines.push('/interface vlan', 'add name=' + customer + ' interface=' + li + ' vlan-id=' + id) }
            if (customer === wanClientName) fail('PPPoE WAN name must differ from customer interface');
            let extraVlans = rows('extraVlans', 3, 3).map(([name, id, parent]) => ({ name: ident(name, 'VLAN name'), id: Number(id), parent: ident(parent, 'VLAN parent') })), createdNames = [customer, wi, li, wanVlan, wanClientName].filter(Boolean); if (mode === 'bridge' && value('bridgeExtra')) createdNames.push(...value('bridgeExtra').split(',').map(s => s.trim())); for (let v of extraVlans) { if (!Number.isInteger(v.id) || v.id < 1 || v.id > 4094) fail('VLAN ID must be 1–4094'); if (createdNames.includes(v.name)) fail('Duplicate interface name: ' + v.name); if (v.parent === wi || v.parent === wanVlan || v.parent === wanClientName || v.name === v.parent) fail('Customer VLAN cannot use WAN as parent'); if (mode === 'bridge' && (v.parent === li || value('bridgeExtra').split(',').map(s => s.trim()).includes(v.parent))) fail('Use the new bridge name as VLAN parent, since customer ports become bridge members'); if (mode === 'vlan' && v.parent === li && v.id === Number(value('vlanId'))) fail('Duplicate VLAN ID on the same parent'); if (extraVlans.some(other => other !== v && other.name === v.parent)) fail('Additional VLAN parent must be an existing interface'); if (extraVlans.some(other => other !== v && other.parent === v.parent && other.id === v.id)) fail('Duplicate VLAN ID on the same parent'); createdNames.push(v.name); lines.push('/interface vlan', 'add name=' + v.name + ' interface=' + v.parent + ' vlan-id=' + v.id) }
            if (wanVlan) { lines.push('# WAN VLAN', '/interface vlan', 'add name=' + wanVlan + ' interface=' + wi + ' vlan-id=' + value('wanVlanId')); wi = wanVlan }
            lines.push('# WAN'); if (value('wanMode') === 'dhcp') lines.push('/ip dhcp-client', 'add interface=' + wi + ' disabled=no use-peer-dns=no'); else if (value('wanMode') === 'pppoe') { wanOut = wanClientName; let user = literal(value('wanPppoeUser'), 'PPPoE WAN username'), pass = literal(value('wanPppoePass'), 'PPPoE WAN password'); let cmd = 'add name=' + wanOut + ' interface=' + wi + ' user=' + user + ' password=' + pass + ' add-default-route=yes use-peer-dns=no disabled=no'; if (value('wanPppoeService')) cmd += ' service-name=' + literal(value('wanPppoeService'), 'PPPoE WAN service'); lines.push('/interface pppoe-client', cmd) } else { let w = value('wanAddress').match(/^([^/]+)\/(\d{1,2})$/); if (!w || +w[2] > 32) fail('Enter a valid WAN address/CIDR'); let wa = fmt(ip(w[1])), gw = fmt(ip(value('wanGateway'))); lines.push('/ip address', 'add address=' + wa + '/' + w[2] + ' interface=' + wi, '/ip route', 'add dst-address=0.0.0.0/0 gateway=' + gw) }
            if (value('wanReach') === 'private') { let endpoint = host(value('vpnEndpoint'), 'L2TP endpoint'), user = literal(value('vpnUser'), 'L2TP username'), pass = literal(value('vpnPass'), 'L2TP password'); let cmd = 'add name=l2tp-radius connect-to=' + endpoint + ' user=' + user + ' password=' + pass + ' add-default-route=no disabled=no'; if (value('vpnIpsec') === 'yes') cmd += ' use-ipsec=yes ipsec-secret=' + literal(value('ipsecSecret'), 'IPsec secret'); lines.push('# RADIUS transport via L2TP', '/interface l2tp-client', cmd, '/ip route', 'add dst-address=' + radius + '/32 gateway=l2tp-radius comment="RADIUS through VPN"'); }
            let profiles = [{ name: 'pppoe_profile', p: { a, e, start, expStart, expEnd }, activePool: 'pppoe_pool' }]; for (let [name, local] of rows('extraProfiles', 2, 2)) { name = ident(name, 'Profile name'); if (profiles.some(p => p.name === name)) fail('Duplicate profile name: ' + name); let p = calcPools(local); for (let old of profiles) if (overlap(p.a, old.p.a)) fail('Active profile subnets overlap: ' + name + ' and ' + old.name); if (overlap(p.a, e)) fail('Active profile overlaps shared expired pool'); profiles.push({ name, p, activePool: 'pool_' + name }) }
            let hotspot = null;
            if ($('enableHotspot').checked) {
                let iface = ident(value('hotspotInterface'), 'Hotspot interface'), wanIfs = [physicalWan, wanVlan, wanClientName, wi].filter(Boolean);
                if (wanIfs.includes(iface)) fail('Hotspot interface cannot be the WAN interface');
                if (mode === 'bridge') { let bridgePorts = [li, ...(value('bridgeExtra') ? value('bridgeExtra').split(',').map(s => s.trim()) : [])]; if (bridgePorts.includes(iface)) fail('Hotspot cannot run on a bridge member port; select the bridge interface instead') }
                let p = calcHotspotSubnet(value('hotspotSubnet'));
                for (let item of profiles) if (overlap(p.a, item.p.a)) fail('Hotspot subnet overlaps PPPoE profile subnet: ' + item.name);
                if (overlap(p.a, e)) fail('Hotspot subnet overlaps the reserved expired-user subnet');
                if (value('wanMode') === 'static') { let w = value('wanAddress').match(/^([^/]+)\/(\d{1,2})$/); if (w && +w[2] <= 32) { let bits = +w[2], size = 2 ** (32 - bits), addr = ip(w[1]), wanNet = { net: Math.floor(addr / size) * size, size }; if (overlap(p.a, wanNet)) fail('Hotspot subnet overlaps the static WAN subnet') } }
                hotspot = { iface, p, dnsName: host(value('hotspotDnsName'), 'Hotspot DNS name'), htmlDirectory: literal(value('hotspotHtmlDirectory'), 'Hotspot HTML directory'), profile: ident(value('hotspotProfileName'), 'Hotspot profile name'), server: ident(value('hotspotServerName'), 'Hotspot server name'), pool: ident(value('hotspotPoolName'), 'DHCP pool name'), dhcp: ident(value('hotspotDhcpName'), 'DHCP server name') };
            }
            let serversList = [{ interface: customer, profile: 'pppoe_profile', service }]; for (let [iface, profile, svc] of rows('extraServers', 3, 3)) { iface = ident(iface, 'PPPoE server interface'); profile = ident(profile, 'PPPoE profile'); if (!profiles.some(p => p.name === profile)) fail('Unknown profile: ' + profile); if ([physicalWan, wanVlan, wanClientName].includes(iface)) fail('PPPoE server cannot use WAN interface'); if (mode === 'bridge' && iface === li) fail('Use bridge name for the customer port in bridge mode'); if (serversList.some(s => s.interface === iface && s.service === svc)) fail('Duplicate PPPoE server interface and service'); serversList.push({ interface: iface, profile, service: literal(svc, 'PPPoE service') }) }
            lines.push('# PPPoE - RADIUS may override profile addresses with its own attributes', '/ip pool'); for (let item of profiles) { let p = item.p; lines.push('add name=' + item.activePool + ' ranges=' + fmt(p.start) + '-' + fmt(p.a.last - 1)) } lines.push('add name=expired_pool ranges=' + fmt(expStart) + '-' + fmt(expEnd)); lines.push('/ppp profile'); for (let item of profiles) lines.push('add name=' + item.name + ' local-address=' + fmt(item.p.a.addr) + ' remote-address=' + item.activePool); lines.push('/interface pppoe-server server'); for (let s of serversList) lines.push('add interface=' + s.interface + ' service-name=' + s.service + ' default-profile=' + s.profile + ' authentication=pap max-mtu=1480 max-mru=1480 disabled=no'); if ($('bindIp').checked) lines.push('/ip address', 'add address=' + fmt(a.addr) + '/' + a.bits + ' interface=' + customer);
            if (hotspot) { let h = hotspot.p, gateway = fmt(h.a.addr), network = fmt(h.a.net) + '/' + h.a.bits; lines.push('# Hotspot - IP address, DHCP and Hotspot server share one interface', '/ip address', 'add address=' + gateway + '/' + h.a.bits + ' network=' + fmt(h.a.net) + ' interface=' + hotspot.iface, '/ip pool', 'add name=' + hotspot.pool + ' ranges=' + fmt(h.start) + '-' + fmt(h.end), '/ip dhcp-server', 'add name=' + hotspot.dhcp + ' interface=' + hotspot.iface + ' address-pool=' + hotspot.pool + ' disabled=no', '/ip dhcp-server network', 'add address=' + network + ' gateway=' + gateway + ' dns-server=' + gateway, '# Restrict router DNS access to trusted LANs in the input firewall', '/ip dns', 'set allow-remote-requests=yes', '/ip hotspot profile', 'add name=' + hotspot.profile + ' dns-name=' + hotspot.dnsName + ' html-directory=' + hotspot.htmlDirectory + ' login-by=cookie,http-chap,http-pap use-radius=yes', '/ip hotspot', 'add name=' + hotspot.server + ' interface=' + hotspot.iface + ' profile=' + hotspot.profile + ' disabled=no') }
            let auth = +value('authPort'), acct = +value('acctPort'); if (!Number.isInteger(auth) || auth < 1 || auth > 65535 || !Number.isInteger(acct) || acct < 1 || acct > 65535) fail('RADIUS ports must be 1–65535'); lines.push('# RADIUS', '/ppp aaa', 'set use-radius=yes accounting=yes', '/radius', 'add service=' + (hotspot ? 'ppp,hotspot' : 'ppp') + ' address=' + radius + ' secret=' + secret + ' require-message-auth=no authentication-port=' + auth + ' accounting-port=' + acct + ' timeout=3s'); if ($('coa').checked) lines.push('# Restrict UDP 1700 from the RADIUS source in input firewall before enabling', '/radius incoming', 'set accept=yes');
            lines.push('# NAT only active customers', '/ip firewall nat'); for (let item of profiles) lines.push('add chain=srcnat src-address=' + fmt(item.p.a.net) + '/' + item.p.a.bits + ' out-interface=' + wanOut + ' action=masquerade comment="active ' + item.name + '"'); if (hotspot) lines.push('add chain=srcnat src-address=' + fmt(hotspot.p.a.net) + '/' + hotspot.p.a.bits + ' out-interface=' + wanOut + ' action=masquerade comment="Hotspot clients"'); if ($('blockExpired').checked) lines.push('# Place this ahead of any broad forward accept rules', '/ip firewall filter', 'add chain=forward src-address=' + fmt(e.net) + '/' + e.bits + ' action=drop comment="expired PPPoE users"')
            lines.push('# Verification (run separately after import)', '# /interface pppoe-server server print detail', '# /ppp active print detail'); if (hotspot) lines.push('# /ip hotspot print detail', '# /ip dhcp-server lease print', '# /radius print detail (verify service=ppp,hotspot)'); else lines.push('# /radius monitor [find where service=ppp]'); lines.push('# /ip route print detail where dst-address=' + radius + '/32', '# /ip pool used print');
            generated = lines.join('\n') + '\n'; $('output').textContent = generated; $('summary').textContent = profiles.map(item => item.name + ': active ' + fmt(item.p.start) + '–' + fmt(item.p.a.last - 1)).join('\n') + '\nShared expired: ' + fmt(expStart) + '–' + fmt(expEnd) + ' (' + fmt(e.net) + '/' + e.bits + ')' + '\n' + serversList.length + ' PPPoE server(s); RADIUS path: ' + (value('wanReach') === 'private' ? 'L2TP' : 'direct') + (hotspot ? '\nHotspot: ' + fmt(hotspot.p.a.addr) + '/' + hotspot.p.a.bits + ' on ' + hotspot.iface + '; DHCP ' + fmt(hotspot.p.start) + '–' + fmt(hotspot.p.end) : ''); $('error').textContent = ''; $('copy').disabled = $('download').disabled = false;
        }
        $('generate').onclick = () => { try { generate() } catch (err) { generated = ''; $('error').textContent = err.message; $('output').textContent = 'Fix the highlighted issue and generate again.'; $('summary').textContent = ''; $('copy').disabled = $('download').disabled = true } };
        $('copy').onclick = async () => { await navigator.clipboard.writeText(generated); $('copy').textContent = 'Copied'; setTimeout(() => $('copy').textContent = 'Copy', 1500) };
        $('download').onclick = () => { let a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([generated], { type: 'text/plain' })); a.download = 'pppoe-radius.rsc'; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 1000) };
